name: Prisma Push Dev

on:
  push:
    branches: [ dev ]

  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    env:
      TRAK_DB_URL: ${{secrets.DEV_TRAK_DB_URL}}

    steps:
      - uses: actions/checkout@master
      - uses: borales/actions-yarn@master
        with:
          cmd: install
      - uses: borales/actions-yarn@master
        with:
          cmd: push

